name = "aiken-lang/deploy-royalities"
version = "0.0.0"
compiler = "v1.1.7"
plutus = "v3"
license = "Apache-2.0"
description = "Aiken contracts for project 'aiken-lang/deploy-royalities'"

[repository]
user = "aiken-lang"
project = "deploy-royalities"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "v2.1.0"
source = "github"

[config]
